# Generated by Django 5.0.1 on 2024-01-25 14:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItemRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.date(2199, 12, 1))),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('month', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Month', to='budget.month')),
            ],
        ),
        migrations.CreateModel(
            name='OpElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valid', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Categorie', to='budget.budgetitem')),
                ('operation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banks.operation')),
            ],
        ),
    ]
